### PR TITLE
Major updates

### PR DESCRIPTION
**Pull request by Ittiz**
Looks like my last pull request bombed, so if you get two that's why.  Take a look and let me know if this can be merged in.  I've made lots of changes.  An important note is I never touched python before playing around with this skill.  So please make sure I made no n00b mistakes  The skill will now look in the config json of Domoticz to find devices IDs by name.  Also the configurations of the skill was moved to the Mycroft settings page.  These two things made the config file obsolete so I removed it.  I also moved to python 3 to to keep up with Mycroft.  I added the ability to operate: scenes, locks and dimmers.

### CODE REVIEW

**Comment by treussart** [comment]
Hi, thanks, but now I can't test your code because I don't have a Mycroft device and domoticz instance. But If you use it and if it works, I can merge.

**Comment by treussart** [comment]
I check the CI and it fails

./__init__.py:52:1: W293 blank line contains whitespace
./__init__.py:55:43: W291 trailing whitespace
./__init__.py:56:39: W291 trailing whitespace
./__init__.py:57:43: W291 trailing whitespace
./__init__.py:58:49: W291 trailing whitespace
./__init__.py:59:43: W291 trailing whitespace
./__init__.py:69:1: W293 blank line contains whitespace
./__init__.py:72:45: E231 missing whitespace after ','
./__init__.py:87:43: W291 trailing whitespace
./__init__.py:88:39: W291 trailing whitespace
./__init__.py:89:43: W291 trailing whitespace
./__init__.py:90:49: W291 trailing whitespace
./__init__.py:91:43: W291 trailing whitespace
./__init__.py:93:9: E265 block comment should start with '# '
./Domoticz.py:4:1: F401 'configparser' imported but unused
./Domoticz.py:5:1: F401 'os' imported but unused
./Domoticz.py:12:1: E302 expected 2 blank lines, found 1
./Domoticz.py:31:5: C901 'Domoticz.switch' is too complex (25)
./Domoticz.py:34:30: E231 missing whitespace after ','
./Domoticz.py:35:31: E231 missing whitespace after ','
./Domoticz.py:41:15: E271 multiple spaces after keyword
./Domoticz.py:43:39: E231 missing whitespace after ','
./Domoticz.py:55:17: F841 local variable 'dtyp' is assigned to but never used
./Domoticz.py:55:40: E231 missing whitespace after ','
./Domoticz.py:56:59: E231 missing whitespace after ','
./Domoticz.py:62:45: E226 missing whitespace around arithmetic operator
./Domoticz.py:66:9: E265 block comment should start with '# '
./Domoticz.py:72:34: E231 missing whitespace after ','
./Domoticz.py:73:35: E231 missing whitespace after ','
./Domoticz.py:83:36: E226 missing whitespace around arithmetic operator
./Domoticz.py:89:36: E226 missing whitespace around arithmetic operator
./Domoticz.py:129:34: E231 missing whitespace after ','
./Domoticz.py:132:39: E231 missing whitespace after ','
./Domoticz.py:134:23: E271 multiple spaces after keyword
./Domoticz.py:136:53: E226 missing whitespace around arithmetic operator
./Domoticz.py:142:23: E271 multiple spaces after keyword
./Domoticz.py:144:53: E226 missing whitespace around arithmetic operator
./Domoticz.py:149:13: E265 block comment should start with '# '
./Domoticz.py:150:13: E265 block comment should start with '# '
The command "flake8 ." exited with 1.

**Comment by Ittiz** [comment]
Ok I'll take a look at that stuff.  Thanks

**Comment by Ittiz** [comment]
I fixed everything except the complex function.  You think it'll get past with that?  Making the that function smaller would be slower and cludgier.

**Comment by treussart** [comment]
You can separate the first part with the 'while' and the test of the result

**Comment by Ittiz** [comment]
I think I got it all set,  I had to split that one function into three, what a headache.

**Review by treussart — APPROVED** [review]
Ok, it seems good

**Pull request merged**
